spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: LUCAS
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        default_schema: LUCAS
        format_sql: true
        use_sql_comments: true
        show_sql: true
